///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Session2_CL
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Session2_CLRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    [RepositoryFolder("c5501f00-a0ff-437c-bd9a-a7846c3cdd0d")]
    public partial class Session2_CLRepository : RepoGenBaseFolder
    {
        static Session2_CLRepository instance = new Session2_CLRepository();
        Session2_CLRepositoryFolders.CLMiamiCatAppFolder _clmiamicat;
        Session2_CLRepositoryFolders.CLMiamiDetailAppFolder _clmiamidetail;
        Session2_CLRepositoryFolders.CLMiamiListAppFolder _clmiamilist;

        /// <summary>
        /// Gets the singleton class instance representing the Session2_CLRepository element repository.
        /// </summary>
        [RepositoryFolder("c5501f00-a0ff-437c-bd9a-a7846c3cdd0d")]
        public static Session2_CLRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Session2_CLRepository() 
            : base("Session2_CLRepository", "/", null, 0, false, "c5501f00-a0ff-437c-bd9a-a7846c3cdd0d", ".\\RepositoryImages\\Session2_CLRepositoryc5501f00.rximgres")
        {
            _clmiamicat = new Session2_CLRepositoryFolders.CLMiamiCatAppFolder(this);
            _clmiamidetail = new Session2_CLRepositoryFolders.CLMiamiDetailAppFolder(this);
            _clmiamilist = new Session2_CLRepositoryFolders.CLMiamiListAppFolder(this);
        }

#region Variables

        string _repoGlobalVar = "";

        /// <summary>
        /// Gets or sets the value of variable repoGlobalVar.
        /// </summary>
        [TestVariable("81bb1405-9575-45bb-b701-f8ea3d93a92c")]
        public string repoGlobalVar
        {
            get { return _repoGlobalVar; }
            set { _repoGlobalVar = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c5501f00-a0ff-437c-bd9a-a7846c3cdd0d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CLMiamiCat folder.
        /// </summary>
        [RepositoryFolder("1128d289-583d-45f0-a3c9-df1b05e5c333")]
        public virtual Session2_CLRepositoryFolders.CLMiamiCatAppFolder CLMiamiCat
        {
            get { return _clmiamicat; }
        }

        /// <summary>
        /// The CLMiamiDetail folder.
        /// </summary>
        [RepositoryFolder("e219cc91-47fe-4ce9-af38-2ad51a06793f")]
        public virtual Session2_CLRepositoryFolders.CLMiamiDetailAppFolder CLMiamiDetail
        {
            get { return _clmiamidetail; }
        }

        /// <summary>
        /// The CLMiamiList folder.
        /// </summary>
        [RepositoryFolder("b55163ff-4f51-454e-b42b-0180a61767d2")]
        public virtual Session2_CLRepositoryFolders.CLMiamiListAppFolder CLMiamiList
        {
            get { return _clmiamilist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    public partial class Session2_CLRepositoryFolders
    {
        /// <summary>
        /// The CLMiamiCatAppFolder folder.
        /// </summary>
        [RepositoryFolder("1128d289-583d-45f0-a3c9-df1b05e5c333")]
        public partial class CLMiamiCatAppFolder : RepoGenBaseFolder
        {
            Session2_CLRepositoryFolders.CategoriesFolder _categories;

            /// <summary>
            /// Creates a new CLMiamiCat  folder.
            /// </summary>
            public CLMiamiCatAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CLMiamiCat", "/dom[@domain~'craigslist.org']/body", parentFolder, 3000, null, true, "1128d289-583d-45f0-a3c9-df1b05e5c333", "")
            {
                _categories = new Session2_CLRepositoryFolders.CategoriesFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1128d289-583d-45f0-a3c9-df1b05e5c333")]
            public virtual Ranorex.BodyTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1128d289-583d-45f0-a3c9-df1b05e5c333")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Categories folder.
            /// </summary>
            [RepositoryFolder("2cd38ee3-0b91-4f85-ae88-fc628f161cde")]
            public virtual Session2_CLRepositoryFolders.CategoriesFolder Categories
            {
                get { return _categories; }
            }
        }

        /// <summary>
        /// The CategoriesFolder folder.
        /// </summary>
        [RepositoryFolder("2cd38ee3-0b91-4f85-ae88-fc628f161cde")]
        public partial class CategoriesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spanqaInfo;

            /// <summary>
            /// Creates a new Categories  folder.
            /// </summary>
            public CategoriesFolder(RepoGenBaseFolder parentFolder) :
                    base("Categories", "div/section/div/div[@class='jobs']", parentFolder, 30000, null, false, "2cd38ee3-0b91-4f85-ae88-fc628f161cde", "")
            {
                _spanqaInfo = new RepoItemInfo(this, "spanQA", "div/div/ul[#'jjj0']/li/a/span[@innertext='software / qa / dba']", 30000, null, "8f5789ed-b324-4f01-b45b-f324ce5103b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cd38ee3-0b91-4f85-ae88-fc628f161cde")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cd38ee3-0b91-4f85-ae88-fc628f161cde")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The spanQA item.
            /// </summary>
            [RepositoryItem("8f5789ed-b324-4f01-b45b-f324ce5103b0")]
            public virtual Ranorex.SpanTag spanQA
            {
                get
                {
                    return _spanqaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The spanQA item info.
            /// </summary>
            [RepositoryItemInfo("8f5789ed-b324-4f01-b45b-f324ce5103b0")]
            public virtual RepoItemInfo spanQAInfo
            {
                get
                {
                    return _spanqaInfo;
                }
            }
        }

        /// <summary>
        /// The CLMiamiDetailAppFolder folder.
        /// </summary>
        [RepositoryFolder("e219cc91-47fe-4ce9-af38-2ad51a06793f")]
        public partial class CLMiamiDetailAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _someinputtagInfo;
            RepoItemInfo _sectionpostInfo;
            RepoItemInfo _linkclInfo;

            /// <summary>
            /// Creates a new CLMiamiDetail  folder.
            /// </summary>
            public CLMiamiDetailAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CLMiamiDetail", "/dom[@domain~'craigslist.org']/body", parentFolder, 3000, null, false, "e219cc91-47fe-4ce9-af38-2ad51a06793f", "")
            {
                _someinputtagInfo = new RepoItemInfo(this, "SomeInputTag", ".//input[#'query']", 30000, null, "c4121c6f-9cfc-413a-97f9-e41d523a9371");
                _sectionpostInfo = new RepoItemInfo(this, "sectionPost", "section/section/section/section[#'postingbody']", 3000, null, "05e3c7fc-565b-4b72-ac9e-02d13d9edc7b");
                _linkclInfo = new RepoItemInfo(this, "linkCL", "section/header[@class='global-header']/a[@innertext='CL']", 30000, null, "5baba088-5410-4043-a542-536ff4f36275");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e219cc91-47fe-4ce9-af38-2ad51a06793f")]
            public virtual Ranorex.BodyTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e219cc91-47fe-4ce9-af38-2ad51a06793f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeInputTag item.
            /// </summary>
            [RepositoryItem("c4121c6f-9cfc-413a-97f9-e41d523a9371")]
            public virtual Ranorex.InputTag SomeInputTag
            {
                get
                {
                    return _someinputtagInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SomeInputTag item info.
            /// </summary>
            [RepositoryItemInfo("c4121c6f-9cfc-413a-97f9-e41d523a9371")]
            public virtual RepoItemInfo SomeInputTagInfo
            {
                get
                {
                    return _someinputtagInfo;
                }
            }

            /// <summary>
            /// The sectionPost item.
            /// </summary>
            [RepositoryItem("05e3c7fc-565b-4b72-ac9e-02d13d9edc7b")]
            public virtual Ranorex.SectionTag sectionPost
            {
                get
                {
                    return _sectionpostInfo.CreateAdapter<Ranorex.SectionTag>(true);
                }
            }

            /// <summary>
            /// The sectionPost item info.
            /// </summary>
            [RepositoryItemInfo("05e3c7fc-565b-4b72-ac9e-02d13d9edc7b")]
            public virtual RepoItemInfo sectionPostInfo
            {
                get
                {
                    return _sectionpostInfo;
                }
            }

            /// <summary>
            /// The linkCL item.
            /// </summary>
            [RepositoryItem("5baba088-5410-4043-a542-536ff4f36275")]
            public virtual Ranorex.ATag linkCL
            {
                get
                {
                    return _linkclInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The linkCL item info.
            /// </summary>
            [RepositoryItemInfo("5baba088-5410-4043-a542-536ff4f36275")]
            public virtual RepoItemInfo linkCLInfo
            {
                get
                {
                    return _linkclInfo;
                }
            }
        }

        /// <summary>
        /// The CLMiamiListAppFolder folder.
        /// </summary>
        [RepositoryFolder("b55163ff-4f51-454e-b42b-0180a61767d2")]
        public partial class CLMiamiListAppFolder : RepoGenBaseFolder
        {
            Session2_CLRepositoryFolders.ListFolder _list;

            /// <summary>
            /// Creates a new CLMiamiList  folder.
            /// </summary>
            public CLMiamiListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CLMiamiList", "/dom[@domain~'craigslist.org']/body", parentFolder, 30000, null, false, "b55163ff-4f51-454e-b42b-0180a61767d2", "")
            {
                _list = new Session2_CLRepositoryFolders.ListFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b55163ff-4f51-454e-b42b-0180a61767d2")]
            public virtual Ranorex.BodyTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b55163ff-4f51-454e-b42b-0180a61767d2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The List folder.
            /// </summary>
            [RepositoryFolder("8d7753d7-7a62-4037-99d7-ee4e4a4e2f38")]
            public virtual Session2_CLRepositoryFolders.ListFolder List
            {
                get { return _list; }
            }
        }

        /// <summary>
        /// The ListFolder folder.
        /// </summary>
        [RepositoryFolder("8d7753d7-7a62-4037-99d7-ee4e4a4e2f38")]
        public partial class ListFolder : RepoGenBaseFolder
        {
            Session2_CLRepositoryFolders.SearchFormFolder _searchform;
            Session2_CLRepositoryFolders.SearchLegendFolder _searchlegend;
            RepoItemInfo _spanrangetoInfo;

            /// <summary>
            /// Creates a new List  folder.
            /// </summary>
            public ListFolder(RepoGenBaseFolder parentFolder) :
                    base("List", "section/form", parentFolder, 30000, null, false, "8d7753d7-7a62-4037-99d7-ee4e4a4e2f38", "")
            {
                _searchform = new Session2_CLRepositoryFolders.SearchFormFolder(this);
                _searchlegend = new Session2_CLRepositoryFolders.SearchLegendFolder(this);
                _spanrangetoInfo = new RepoItemInfo(this, "spanRangeTo", "div[@class='search-legend']/div/span[@class='buttons']/span[@class~'pagenum']/span/span[@class='rangeTo']", 30000, null, "5633678b-9f0b-4246-bf9a-986e8ec51d06");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d7753d7-7a62-4037-99d7-ee4e4a4e2f38")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d7753d7-7a62-4037-99d7-ee4e4a4e2f38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The spanRangeTo item.
            /// </summary>
            [RepositoryItem("5633678b-9f0b-4246-bf9a-986e8ec51d06")]
            public virtual Ranorex.SpanTag spanRangeTo
            {
                get
                {
                    return _spanrangetoInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The spanRangeTo item info.
            /// </summary>
            [RepositoryItemInfo("5633678b-9f0b-4246-bf9a-986e8ec51d06")]
            public virtual RepoItemInfo spanRangeToInfo
            {
                get
                {
                    return _spanrangetoInfo;
                }
            }

            /// <summary>
            /// The SearchForm folder.
            /// </summary>
            [RepositoryFolder("7fc0428d-0bf7-47ed-a819-d312f091eb4e")]
            public virtual Session2_CLRepositoryFolders.SearchFormFolder SearchForm
            {
                get { return _searchform; }
            }

            /// <summary>
            /// The SearchLegend folder.
            /// </summary>
            [RepositoryFolder("a282a32d-552c-4baf-93cb-6de04de1b237")]
            public virtual Session2_CLRepositoryFolders.SearchLegendFolder SearchLegend
            {
                get { return _searchlegend; }
            }
        }

        /// <summary>
        /// The SearchFormFolder folder.
        /// </summary>
        [RepositoryFolder("7fc0428d-0bf7-47ed-a819-d312f091eb4e")]
        public partial class SearchFormFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputsearchInfo;
            RepoItemInfo _buttonsearchInfo;

            /// <summary>
            /// Creates a new SearchForm  folder.
            /// </summary>
            public SearchFormFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchForm", "div[@class='querybox']", parentFolder, 30000, null, false, "7fc0428d-0bf7-47ed-a819-d312f091eb4e", "")
            {
                _inputsearchInfo = new RepoItemInfo(this, "inputSearch", "input[#'query']", 30000, null, "dbfc1970-be67-43af-a942-c9e20486cb47");
                _buttonsearchInfo = new RepoItemInfo(this, "buttonSearch", "button/span", 30000, null, "568f1cf5-0256-45db-bf5c-5c0512bb0d58");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7fc0428d-0bf7-47ed-a819-d312f091eb4e")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7fc0428d-0bf7-47ed-a819-d312f091eb4e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The inputSearch item.
            /// </summary>
            [RepositoryItem("dbfc1970-be67-43af-a942-c9e20486cb47")]
            public virtual Ranorex.InputTag inputSearch
            {
                get
                {
                    return _inputsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The inputSearch item info.
            /// </summary>
            [RepositoryItemInfo("dbfc1970-be67-43af-a942-c9e20486cb47")]
            public virtual RepoItemInfo inputSearchInfo
            {
                get
                {
                    return _inputsearchInfo;
                }
            }

            /// <summary>
            /// The buttonSearch item.
            /// </summary>
            [RepositoryItem("568f1cf5-0256-45db-bf5c-5c0512bb0d58")]
            public virtual Ranorex.SpanTag buttonSearch
            {
                get
                {
                    return _buttonsearchInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The buttonSearch item info.
            /// </summary>
            [RepositoryItemInfo("568f1cf5-0256-45db-bf5c-5c0512bb0d58")]
            public virtual RepoItemInfo buttonSearchInfo
            {
                get
                {
                    return _buttonsearchInfo;
                }
            }
        }

        /// <summary>
        /// The SearchLegendFolder folder.
        /// </summary>
        [RepositoryFolder("a282a32d-552c-4baf-93cb-6de04de1b237")]
        public partial class SearchLegendFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new SearchLegend  folder.
            /// </summary>
            public SearchLegendFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchLegend", "div[@class='search-legend']/div/span[@class='buttons']", parentFolder, 60000, null, false, "a282a32d-552c-4baf-93cb-6de04de1b237", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a282a32d-552c-4baf-93cb-6de04de1b237")]
            public virtual Ranorex.SpanTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a282a32d-552c-4baf-93cb-6de04de1b237")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}